base_url = "https://acm.umn.edu/"
build_search_index = false
compile_sass = true
generate_rss = true
highlight_code = true
title = "ACM UMN"

# Enable if you want to check, but this is slow and dip doesn't send us back logs afaik.
# check_external_links = true

taxonomies = [
	{name = "tags", rss = true}
]

[extra]
nav_links = [
    { url = "/events", text = "Events" },
    { url = "/officers", text = "Officers" },
    { url = "/newsletters", text = "Newsletters" },
    { url = "/meeting-minutes", text = "Meeting Minutes" },
]
